version: '3.9'

services:
  oltp-db:
    image: postgres:latest
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8090:8080"
    restart: always

volumes:
  postgres_data:
